version: '2'
services:
  master:
    container_name: hadoop-master
    image: centos_sshd:v1
    networks:
      network:
        ipv4_address: 172.20.0.2
  slave1:
    container_name: hadoop-slave1
    image: centos_sshd:v1
    networks:
      network:
        ipv4_address: 172.20.0.3
  slave2:
    container_name: hadoop-slave2
    image: centos_sshd:v1
    networks:
      network:
        ipv4_address: 172.20.0.4
networks:
  network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
